---

git_repo: git@github.com:paolopaolopaolo/light-sensor.git
repo_name: light-sensor

project_name: lightsensor
application_name: lightsensor

git_ssh_pub_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQChBQHDV1vSnd3aK1WQXNavEanAWh2AJNlZB8+RRxED00A1QA7/0rDf8hb+ZVyZioe4B3QhlxiRFmssrGuEdGGLIkpYFk4hnMzt//apVcKzvzAnSYqrXFeUsR1eUKb6cpEqiJ8AwMpdyrrpNAc4DuAWRPzSu8u+DLcI2/tjM1xw+WLyAdr+vfabDRy/C052V6Ckgp9vDD0bkkSJpolONJQ+W1W5RRxxNAYG95Uzdl0JmU/ch2JbDphr4n6aX5yGTrcUCIXnhScxHC+5mEZrDAU6gY5GauTrmlXMt8vmPlRZqskUzavrUAMPSCByjdM1Eb+Xp/JmMA2NWAZwKokeGAH31YD8pc5yh9fNpcTxbqdMRy0ASIhaopi8ITP4FhtWy6+26D50x4x8sCSGz4Y0+gkFKjDu5I3ltq4VmaFlAvonDxkOhyU8DjmQEyov7FFyEuo5wu9SBRiP7xyQ4AfRsKtAOzpggAx69CgFhyoFLy2J/LMSYywqDDeDBDpzeVm32blq1HC1beaGZ+8updbtXq9epX+XkAi7o15qbnx7fOZGkLaplofcvHePZY4tlSlo5SFiqjy5G84aTaQZZius4U9XGGxi8+zwfEDMdXN846zaS/usMdvRsHDqDawGrIV/194a5+60tvwaedqyZGNZqdJx5QQjAcWlc/zV4xOoXKQPbQ==
git_ssh_priv_key:  |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKQIBAAKCAgEAoQUBw1db0p3d2itVkFzWrxGpwFodgCTZWQfPkUcRA9NANUAO
  /9Kw3/IW/mVcmYqHuAd0IZcYkRZrLKxrhHRhiyJKWBZOIZzM7f/2qVXCs78wJ0mK
  q1xXlLEdXlCm+nKRKoifAMDKXcq66TQHOA7gFkT80rvLvgy3CNv7YzNccPli8gHa
  /r32mw0cvwtOdlegpIKfbww9G5JEiaaJTjSUPltVuUUccTQGBveVM3ZdCZlP3Idi
  Ww6Ya+J+ml+chk63FAiF54UnMRwvuZhGawwFOoGORmrk65pVzLfL5j5UWarJFM2r
  61ADD0ggco3TNRG/l6fyZjANjVgGcCqJHhgB99WA/KXOcofXzaXE8W6nTEctAEiI
  WqKYvCEz+BYbVsuvtug+dMeMfLAkhs+GNPoJBSow7uSN5bauFZmhZQL6Jw8ZDocl
  PA45kBMqL+xRchLqOcLvUgUYj+8ckOAH0bCrQDs6YIAMevQoBYcqBS8tifyzEmMs
  Kgw3gwQ6c3lZt9m5atRwtW3mhmfvLqXW7V6vXqV/l5AIu6Neam58e3zmRpC2qZaH
  3Lx3j2WOLZUpaOUhYqo8uRvOGk2kGWYrrOFPVxhsYvPs8HxAzHVzfOOs2kv7rDHb
  0bBw6g2sBqyFf9feGufutLb8GnnasmRjWanSceUEIwHFpXP81eMTqFykD20CAwEA
  AQKCAgAtdABfaBWfirjJkVoB+nMP0Giex9F0DvLb0vyhAfKnpcaGQaL6TDtpvCkJ
  fwt4vEY7iL8bjE9/BVkTr0hah4/ResiJvSIpEt42gP7cJj1kCCBLttLSNKr0alrj
  +Nhp8lVQMGjSCZoWh9fjZLB0/p37K1ZDFogZCfXRJmf8RM9fhMaNkkCDkJRAiJ8I
  vuRTO8E5LzZaXpYRZmS6hqxTyzvdrmKwffXdbtYUuWcAs/TndMO6eO0mzyPvsGwU
  n9DLiQTdPtqt1ESP9Gj0dyvJpAcF0PScpCgi6do2g9unDwk4lqFUogpZzqhOdAnU
  zHxGitAOu3YNqprov2Rx3U//kr9bB6zRYJ8H6c4R1Z4SUgF2nrvmTTEgVWGDxqBL
  ZBVRSEtiJdHaPQVql5k1UMTYCaHwDAc6ind3Uk2BTaEzIGKQkFO328O1XZOaVsjb
  J85Np4l0tM3iRd8yPxyfNhNSrrCWie7eG0uZeNqADYxQt5Jtg5deZ3vRZqMToW4x
  X9lkkXeLnQzT53xf8wC2tGbk3UJeDJ/5s4SETgSDqAeocsnqh4yreQIiP2zG9MVZ
  pjDuOy079TkImkbSJRdbJU40Co9gCnA2uuW1DEX453sZUeOSxgG9oaVlKeGUSkYe
  Ld37z8LzdaMUW1kKaUPDLXTnFsUQqsUVIXcJq7ZeQYv+cmA4AQKCAQEAvsK4yYsp
  i014ClIetzSicp501+jjqbeLYZFsYd9WQPyVHQD/tDGY8/8Lbopig2D9XaVv8zGe
  b/LQvCZ/+7pwBABfkZTINe1n7k8ut+Oa404MsX0MxGbwBYi3imf4UDhgiZHwx+rW
  LWyPphJDpQFMImyWkgrOTE27fi1ZOQFpSg+xoHZR4dGHwXZ4JIdchqvglBrwWVXm
  /QWWZ6a/nrewbLNlHl8Mh4RE2pgrrcqCqTCZqgOUQdInexUv3ijUFkHX7xjx+ahH
  /3iE14pJw9WlrR5mA/W4GNdevotvx3z+69ukjlT09R6yXKHzRfwTpZqpsKsE/ZaV
  jL2vuPRoeGKagQKCAQEA2BZs2xhFC4NdeLBuFjZgitlrtWCQgoNMbBvZFHsHRbkF
  U6A0DaibtXOgGtLZ2KgB2WV9QkGhMqCmhFRqPLHkR95JAls+hhZbQW2MWVQG0WoU
  Z9Bhbg/GkjGDR/kQpRgw+GClKKMZj7ah4gdXNhsfff4OdWHixeJxDsyUVAMBMh4c
  xZn0Ht6z7z/X7AGO54XMkfJD3XEFNpTOUWcUc5kQcma/U36eQiMxR/tJpT7YVudx
  WH6yAcoujD3DjRWz+VWjjrnhaJPPtEIJU5LzgxLBIsJvCX25SnUXyvhl6K8krrKL
  tR3YWuRbS8wkHjx6tyqr7BcjywDpOuHMqZ7Vo7wG7QKCAQBbzHUEeDWr1cH4pYAm
  hevO4LY12NsGJ0+pykOv7bwiVeqkJIDpBB0o/glQTsQNmTUURbLUA4LNOLp+cMCS
  MSwKoOtcsY6PdQnYwr4mvB8jV8H//7+PHEJRR3Ob5WC3qgm66kJG0pnzDhUqxAtN
  coxi3IKxEQYp7hZWKBiRuD4k59yA7a+FzkFYNlymp4U9QaU3YKddNluMU44Hn1UD
  Wj5KcSIuNWtgI6TG1QfgAF5UcRDhogtMiYd6Ub3RWTCG7XSumQCJNhQ/uo2i8+d/
  mGa8Iq7RJQRM4Ae2Bn/qLhq3AeH0pKmk8/q9XSom+aGyxfT3EbW7GyYornfLt8I2
  fK0BAoIBAQC4FqK2JH7tyAQhhWzDz59/qqpv4sw549F/aFoPcKBJbc5z589ws2uz
  scV8FJUyVi79HdEQWQkTMHmr0p6PBp4L+/sG3uTtJq6nlsQydbs5PL4VkxjtwtLQ
  SQ4mirD7dRiDARKzBAAKxvQysz5BAepaU83Ngo7HNppKmU7kI4spPy4TyYyHoAJ6
  mFFC5jDwXLRiwZm/VUGztiHuh3qM4KF6VL46S2xXu9OIFzQuatOzdYjCc20CyVPO
  de/aidrBV4v3U7QMe6A/WOLJKC/8QkX3bt1ZoJnyLL8QU32+NTdy/Pi4W6yuAk0k
  zc0XVT7WPKwqfawojaYkW6kX+BDZZJ4hAoIBAQCBrHz+7XHxs3y3QfKsfC73v8TA
  8/8+i4/bakS6RajgyClqfDHYeDAHnsldGeWdgR08DqYJKMVU6EZ4kFutvmnVLFHU
  ioGGWVhUKPbT24SSja+NK/BdmjSegyExAGNP6vCQlkNdJtXaf5J+vn1Fr779xy9G
  DRUqnZCxrvYRePohpCnf7DpcmoXLqm4oBv9q6uLzVm2NAQ+lBV39UEeaV9O9KtJB
  dL/EtF2o+AGTcwxrFzXNY2yGiptPsXiV1NMnILoqHxGpf66h57L8jfi8yy03s9Z2
  81uMrt36++7hAqPF0oe6+de4Au+nvSc9GLLrj3Dv1dsk55MqXNwd5be52CVL
  -----END RSA PRIVATE KEY-----

